CHEMICAL_DB = {
    'C6H12O6': {
        'Name': 'glucose',
        'C': 6,
        'H': 12.0,
        'O': 6.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -1264.2,
        'Free-energy of formation (kJ/mol)': {'Amend': -919.8, 'eQ pH=0': -905.7, 'eQ pH=7.5': -392.3, 'Kleerebezem': -917.2},
        'Molar mass (g/mol)': 180.0,
    },

    'glucose': 'C6H12O6',

    'C6H12O6 (galactose)': {
        'Name': 'galactose',
        'C': 6,
        'H': 12.0,
        'O': 6.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -1264.2,
        'Free-energy of formation (kJ/mol)': {'Amend': -913.8, 'eQ pH=0': -904.1, 'eQ pH=7.5': -385.3, 'Kleerebezem': -917.2},
        'Molar mass (g/mol)': 180.0,
    },

    'galactose': 'C6H12O6 (galactose)',

    'C6H12O6 (mannose)': {
        'Name': 'mannose',
        'C': 6,
        'H': 12.0,
        'O': 6.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -1264.2,
        'Free-energy of formation (kJ/mol)': {'Amend': -912.8, 'eQ pH=0': -903.1, 'eQ pH=7.5': -389.6, 'Kleerebezem': -917.2},
        'Molar mass (g/mol)': 180.0,
    },

    'mannose': 'C6H12O6 (mannose)',

    'C6H12O6 (fructose)': {
        'Name': 'fructose',
        'C': 6,
        'H': 12.0,
        'O': 6.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -1264.2,
        'Free-energy of formation (kJ/mol)': {'Amend': -915.6, 'eQ pH=0': -905.9, 'eQ pH=7.5': -392.4, 'Kleerebezem': -917.2},
        'Molar mass (g/mol)': 180.0,
    },

    'fructose': 'C6H12O6 (fructose)',

    'C6H14O6': {
        'Name': 'mannitol',
        'C': 6,
        'H': 14.0,
        'O': 6.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': -0.333333333333333,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -1337.5,
        'Free-energy of formation (kJ/mol)': {'Amend': -942.6, 'eQ pH=0': -932.1, 'eQ pH=7.5': -333.1, 'Kleerebezem': -942.6},
        'Molar mass (g/mol)': 182.0,
    },

    'mannitol': 'C6H14O6',

    'C3H8O3': {
        'Name': 'glycerol',
        'C': 3,
        'H': 8.0,
        'O': 3.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': -0.666666666666667,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -676.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -488.5, 'eQ pH=0': -487.3, 'eQ pH=7.5': -145.0, 'Kleerebezem': -488.5},
        'Molar mass (g/mol)': 92.0,
    },

    'glycerol': 'C3H8O3',

    'C3H3O3-1': {
        'Name': 'pyruvate',
        'C': 3,
        'H': 3.0,
        'O': 3.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': 0.6666666666666665,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -596.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -474.6, 'eQ pH=0': -481.4, 'eQ pH=7.5': -338.1, 'Kleerebezem': -474.6},
        'Molar mass (g/mol)': 87.0,
    },

    'pyruvate': 'C3H3O3-1',

    'H+1': {
        'Name': 'proton',
        'C': 0,
        'H': 1.0,
        'O': 0.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 1,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': 0.0,
        'Free-energy of formation (kJ/mol)': {'Amend': 0.0, 'eQ pH=0': 0.0, 'eQ pH=7.5': 0.0, 'Kleerebezem': 0.0},
        'Molar mass (g/mol)': 1.0,
    },

    'proton': 'H+1',

    'O2': {
        'Name': 'oxygen',
        'C': 0,
        'H': 0.0,
        'O': 2.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': 0.0,
        'Free-energy of formation (kJ/mol)': {'Amend': 16.54, 'eQ pH=0': 16.4, 'eQ pH=7.5': 16.4, 'Kleerebezem': 0.0},
        'Molar mass (g/mol)': 32.0,
    },

    'oxygen': 'O2',

    'H2O': {
        'Name': 'water',
        'C': 0,
        'H': 2.0,
        'O': 1.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'l',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -285.8,
        'Free-energy of formation (kJ/mol)': {'Amend': -237.18, 'eQ pH=0': -236.5, 'eQ pH=7.5': -157.28, 'Kleerebezem': -237.2},
        'Molar mass (g/mol)': 18.0,
    },

    'water': 'H2O',

    'NH4+1': {
        'Name': 'ammonium',
        'C': 0,
        'H': 4.0,
        'O': 0.0,
        'N': 1.0,
        'S': 0,
        'Mn': 0,
        'Charge': 1,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -133.3,
        'Free-energy of formation (kJ/mol)': {'Amend': -79.45, 'eQ pH=0': -79.5, 'eQ pH=7.5': 91.6, 'Kleerebezem': -79.4},
        'Molar mass (g/mol)': 18.0,
    },

    

    'ammonium': 'NH4+1',

    'CHO3-1': {
        'Name': 'bicarbonate',
        'C': 1,
        'H': 1.0,
        'O': 3.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': 4.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -692.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -586.94, 'eQ pH=0': -606.1, 'eQ pH=7.5': -386.0, 'Kleerebezem': -586.9},
        'Molar mass (g/mol)': 61.0,
    },

    'bicarbonate': 'CHO3-1',

    'C2H3O2-1': {
        'Name': 'acetate',
        'C': 2,
        'H': 3.0,
        'O': 2.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -485.8,
        'Free-energy of formation (kJ/mol)': {'Amend': -369.33, 'eQ pH=0': -391.1, 'eQ pH=7.5': -238.4, 'Kleerebezem': -369.4},
        'Molar mass (g/mol)': 59.0,
    },

    'acetate': 'C2H3O2-1',

    'C3H5O3-1': {
        'Name': 'lactate',
        'C': 3,
        'H': 5.0,
        'O': 3.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -687.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -512.67, 'eQ pH=0': -529.5, 'eQ pH=7.5': -295.6, 'Kleerebezem': -517.1},
        'Molar mass (g/mol)': 89.0,
    },

    'lactate': 'C3H5O3-1',

    'C2H6O': {
        'Name': 'ethanol',
        'C': 2,
        'H': 6.0,
        'O': 1.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': -2.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -288.3,
        'Free-energy of formation (kJ/mol)': {'Amend': -181.3, 'eQ pH=0': -174.3, 'eQ pH=7.5': 82.4, 'Kleerebezem': -181.8},
        'Molar mass (g/mol)': 46.0,
    },

    'ethanol': 'C2H6O',

    'C2O4-2': {
        'Name': 'oxalate',
        'C': 2,
        'H': 0.0,
        'O': 4.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -2,
        'NOS': 3.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -818.8,
        'Free-energy of formation (kJ/mol)': {'Amend': -674.05, 'eQ pH=0': -703.6, 'eQ pH=7.5': -677.6, 'Kleerebezem': -674.0},
        'Molar mass (g/mol)': 88.0,
    },

    'oxalate': 'C2O4-2',

    'CHO2-1': {
        'Name': 'formate',
        'C': 1,
        'H': 1.0,
        'O': 2.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': 2.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -410.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -350.88, 'eQ pH=0': -370.9, 'eQ pH=7.5': -305.4, 'Kleerebezem': -351.0},
        'Molar mass (g/mol)': 45.0,
    },

    'formate': 'CHO2-1',

    'NO3-1': {
        'Name': 'nitrate',
        'C': 0,
        'H': 0.0,
        'O': 3.0,
        'N': 1.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -173.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -110.91, 'eQ pH=0': -109.5, 'eQ pH=7.5': -109.5, 'Kleerebezem': -111.3},
        'Molar mass (g/mol)': 62.0,
    },

    'nitrate': 'NO3-1',

    'N2O': {
        'Name': 'nitrous oxide',
        'C': 0,
        'H': 0.0,
        'O': 1.0,
        'N': 2.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': 82.0,
        'Free-energy of formation (kJ/mol)': {'Amend': 113.38, 'eQ pH=0': 104.2, 'eQ pH=7.5': 104.2, 'Kleerebezem': 104.2},
        'Molar mass (g/mol)': 44.0,
    },

    'nitrous oxide': 'N2O',

    'N2': {
        'Name': 'dinitrogen',
        'C': 0,
        'H': 0.0,
        'O': 0.0,
        'N': 2.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': 0.0,
        'Free-energy of formation (kJ/mol)': {'Amend': 18.18, 'eQ pH=0': 18.7, 'eQ pH=7.5': 18.7, 'Kleerebezem': 0.0},
        'Molar mass (g/mol)': 28.0,
    },

    'dinitrogen': 'N2',

    'CO2': {
        'Name': 'carbon dioxide',
        'C': 1,
        'H': 0.0,
        'O': 2.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 4.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -393.5,
        'Free-energy of formation (kJ/mol)': {'Amend': -385.98, 'eQ pH=0': -386.0, 'eQ pH=7.5': -386.0, 'Kleerebezem': -394.4},
        'Molar mass (g/mol)': 44.0,
    },

    'carbon dioxide': 'CO2',

    'H2': {
        'Name': 'hydrogen',
        'C': 0,
        'H': 2.0,
        'O': 0.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': 0.0,
        'Free-energy of formation (kJ/mol)': {'Amend': 17.72, 'eQ pH=0': 19.2, 'eQ pH=7.5': 104.8, 'Kleerebezem': 17.72},
        'Molar mass (g/mol)': 2.0,
    },

    'hydrogen': 'H2',

    'NO2-1': {
        'Name': 'nitrite',
        'C': 0,
        'H': 0.0,
        'O': 2.0,
        'N': 1.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -107.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -32.22, 'eQ pH=0': -72.9, 'eQ pH=7.5': -30.1, 'Kleerebezem': -32.2},
        'Molar mass (g/mol)': 46.0,
    },

    'nitrite': 'NO2-1',

    'C4H4O4-2': {
        'Name': 'succinate',
        'C': 4,
        'H': 4.0,
        'O': 4.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -2,
        'NOS': 0.5,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -909.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -687.77, 'eQ pH=0': -726.6, 'eQ pH=7.5': -507.6, 'Kleerebezem': -690.2},
        'Molar mass (g/mol)': 116.0,
    },

    'succinate': 'C4H4O4-2',

    'C4H2O4-2': {
        'Name': 'fumarate',
        'C': 4,
        'H': 2.0,
        'O': 4.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -2,
        'NOS': 1.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -777.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -604.2, 'eQ pH=0': -639.6, 'eQ pH=7.5': -515.7, 'Kleerebezem': -604.2},
        'Molar mass (g/mol)': 114.0,
    },

    'fumarate': 'C4H2O4-2',

    'C2H3O3-1': {
        'Name': 'glycolate',
        'C': 2,
        'H': 3.0,
        'O': 3.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': 1.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -648.5,
        'Free-energy of formation (kJ/mol)': {'Amend': -506.98, 'eQ pH=0': -549.7, 'eQ pH=7.5': -402.9, 'Kleerebezem': -517.6},
        'Molar mass (g/mol)': 87.0,
    },

    'glycolate': 'C2H3O3-1',

    'MnO2': {
        'Name': 'manganese dioxide',
        'C': 0,
        'H': 0.0,
        'O': 2.0,
        'N': 0.0,
        'S': 0,
        'Mn': 1,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 's',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -520.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -465.1, 'eQ pH=0': -465.1, 'eQ pH=7.5': -465.1, 'Kleerebezem': -465.1},
        'Molar mass (g/mol)': 87.0,
    },

    'manganese dioxide': 'MnO2',

    'Mn+2': {
        'Name': 'manganese II+ ion',
        'C': 0,
        'H': 0.0,
        'O': 0.0,
        'N': 0.0,
        'S': 0,
        'Mn': 1,
        'Charge': 2,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -220.7,
        'Free-energy of formation (kJ/mol)': {'Amend': -230.54, 'eQ pH=0': -228.0, 'eQ pH=7.5': -228.0, 'Kleerebezem': -228.0},
        'Molar mass (g/mol)': 55.0,
    },

    'manganese II+ ion': 'Mn+2',

    'CH3NH3+1': {
        'Name': 'methylamine',
        'C': 1,
        'H': 3.0,
        'O': 0.0,
        'N': 1.0,
        'S': 0,
        'Mn': 0,
        'Charge': 1,
        'NOS': 1.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -70.2,
        'Free-energy of formation (kJ/mol)': {'Amend': 21.08, 'eQ pH=0': -35.8, 'eQ pH=7.5': 220.9, 'Kleerebezem': 20.7},
        'Molar mass (g/mol)': 32.0,
    },

    'methylamine': 'CH3NH3+1',

    'CH4O': {
        'Name': 'methanol',
        'C': 1,
        'H': 4.0,
        'O': 1.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': -2.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -245.9,
        'Free-energy of formation (kJ/mol)': {'Amend': -175.94, 'eQ pH=0': -172.0, 'eQ pH=7.5': -0.9, 'Kleerebezem': -175.4},
        'Molar mass (g/mol)': 32.0,
    },

    'methanol': 'CH4O',

    'C6H5O7-3': {
        'Name': 'citrate',
        'C': 6,
        'H': 5.0,
        'O': 7.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -3,
        'NOS': 1.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -1515.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -1168.3, 'eQ pH=0': -1229.2, 'eQ pH=7.5': -952.0, 'Kleerebezem': -1168.3},
        'Molar mass (g/mol)': 189.0,
    },

    'citrate': 'C6H5O7-3',

    'C4H4O5-2': {
        'Name': 'malate',
        'C': 4,
        'H': 4.0,
        'O': 5.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -2,
        'NOS': 1.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -843.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -845.0, 'eQ pH=0': -883.8, 'eQ pH=7.5': -670.0, 'Kleerebezem': -845.1},
        'Molar mass (g/mol)': 132.0,
    },

    'malate': 'C4H4O5-2',

    'HS-1': {
        'Name': 'bisulfide',
        'C': 0,
        'H': 1.0,
        'O': 0.0,
        'N': 0.0,
        'S': 1,
        'Mn': 0,
        'Charge': -1,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -17.6,
        'Free-energy of formation (kJ/mol)': {'Amend': 11.97, 'eQ pH=0': 11.6, 'eQ pH=7.5': 54.4, 'Kleerebezem': 12.1},
        'Molar mass (g/mol)': 33.0,
    },

    'bisulfide': 'HS-1',

    'C4H7O2-1': {
        'Name': 'butyrate',
        'C': 4,
        'H': 7.0,
        'O': 2.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': -1.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -535.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -354.18, 'eQ pH=0': -374.1, 'eQ pH=7.5': -48.2, 'Kleerebezem': -352.6},
        'Molar mass (g/mol)': 87.0,
    },

    'butyrate': 'C4H7O2-1',

    'SO4-2': {
        'Name': 'sulfate',
        'C': 0,
        'H': 0.0,
        'O': 4.0,
        'N': 0.0,
        'S': 1,
        'Mn': 0,
        'Charge': -2,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -909.6,
        'Free-energy of formation (kJ/mol)': {'Amend': -744.46, 'eQ pH=0': -755.9, 'eQ pH=7.5': -748.1, 'Kleerebezem': -744.6},
        'Molar mass (g/mol)': 96.0,
    },

    'sulfate': 'SO4-2',

    'C3H5O2-1': {
        'Name': 'propionate',
        'C': 3,
        'H': 5.0,
        'O': 2.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': -0.666666666666667,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -510.4,
        'Free-energy of formation (kJ/mol)': {'Amend': -363.09, 'eQ pH=0': -383.0, 'eQ pH=7.5': -143.6, 'Kleerebezem': -361.1},
        'Molar mass (g/mol)': 73.0,
    },

    'propionate': 'C3H5O2-1',

    'H2S': {
        'Name': 'hydrogen sulfide',
        'C': 0,
        'H': 2.0,
        'O': 0.0,
        'N': 0.0,
        'S': 1,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -39.75,
        'Free-energy of formation (kJ/mol)': {'Amend': -27.92, 'eQ pH=0': 11.6, 'eQ pH=7.5': 54.4, 'Kleerebezem': -34.0},
        'Molar mass (g/mol)': 34.0,
    },

    'hydrogen sulfide': 'H2S',

    'SO3-2': {
        'Name': 'sulfite',
        'C': 0,
        'H': 0.0,
        'O': 3.0,
        'N': 0.0,
        'S': 1,
        'Mn': 0,
        'Charge': -2,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -635.5,
        'Free-energy of formation (kJ/mol)': {'Amend': -486.6, 'eQ pH=0': -533.5, 'eQ pH=7.5': -487.3, 'Kleerebezem': -486.6},
        'Molar mass (g/mol)': 80.0,
    },

    'sulfite': 'SO3-2',

    'S': {
        'Name': 'sulfur (rhombic)',
        'C': 0,
        'H': 0.0,
        'O': 0.0,
        'N': 0.0,
        'S': 1,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 's',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': 0.0,
        'Free-energy of formation (kJ/mol)': {'Amend': 0.0, 'eQ pH=0': 0.0, 'eQ pH=7.5': 0.0, 'Kleerebezem': 0.0},
        'Molar mass (g/mol)': 32.0,
    },

    'sulfur (rhombic)': 'S',

    'C4H10O': {
        'Name': '1-butanol',
        'C': 4,
        'H': 10.0,
        'O': 1.0,
        'N': 1.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': -1.25,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -328.0,
        'Free-energy of formation (kJ/mol)': {'Amend': -162.51, 'eQ pH=0': -163.6, 'eQ pH=7.5': 264.3, 'Kleerebezem': -171.8},
        'Molar mass (g/mol)': 74.0,
    },

    '1-butanol': 'C4H10O',

    'CH4': {
        'Name': 'methane',
        'C': 1,
        'H': 4.0,
        'O': 0.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': -4.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -74.8,
        'Free-energy of formation (kJ/mol)': {'Amend': -34.46, 'eQ pH=0': -31.1, 'eQ pH=7.5': 140.0, 'Kleerebezem': -34.46},
        'Molar mass (g/mol)': 16.0,
    },

    'methane': 'CH4',

    'CH2O': {
        'Name': 'formaldehyde',
        'C': 1,
        'H': 2.0,
        'O': 1.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -150.2,
        'Free-energy of formation (kJ/mol)': {'Amend': -130.5, 'eQ pH=0': -122.1, 'eQ pH=7.5': -36.5, 'Kleerebezem': -130.5},
        'Molar mass (g/mol)': 30.0,
    },

    'formaldehyde': 'CH2O',

    'C16H34': {
        'Name': 'hexadecane',
        'C': 16,
        'H': 34.0,
        'O': 0.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': -2.125,
        'Phase': 'l',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -456.1,
        'Free-energy of formation (kJ/mol)': {'Amend': 49.44, 'eQ pH=0': 49.44, 'eQ pH=7.5': 1403.6, 'Kleerebezem': 49.44},
        'Molar mass (g/mol)': 226.0,
    },

    'hexadecane': 'C16H34',

    'C12H22O11': {
        'Name': 'lactose',
        'C': 12,
        'H': 22.0,
        'O': 11.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -2233.8,
        'Free-energy of formation (kJ/mol)': {'Amend': -1565.9, 'eQ pH=0': -1557.2, 'eQ pH=7.5': -615.9, 'Kleerebezem': -1565.9},
        'Molar mass (g/mol)': 342.0,
    },

    'lactose': 'C12H22O11',

    'C3H6O2N-1': {
        'Name': 'alanine',
        'C': 3,
        'H': 6.0,
        'O': 2.0,
        'N': 1.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -315.1,
        'Free-energy of formation (kJ/mol)': {'Amend': -371.59, 'eQ pH=0': -376.6, 'eQ pH=7.5': -63.0, 'Kleerebezem': -315.1},
        'Molar mass (g/mol)': 88.0,
    },

    'alanine': 'C3H6O2N-1',

    'C4H8O2 (acetoin)': {
        'Name': 'acetoin',
        'C': 4,
        'H': 8.0,
        'O': 2.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': -1.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -395.98,
        'Free-energy of formation (kJ/mol)': {'Amend': -280.0, 'eQ pH=0': -286.3, 'eQ pH=7.5': 56.0, 'Kleerebezem': -280.0},
        'Molar mass (g/mol)': 88.0,
    },

    'acetoin': 'C4H8O2 (acetoin)',

    'C4H10O2': {
        'Name': '2.3-butanediol',
        'C': 4,
        'H': 10.0,
        'O': 2.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': -1.5,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -505.3,
        'Free-energy of formation (kJ/mol)': {'Amend': -322.0, 'eQ pH=0': -319.7, 'eQ pH=7.5': 108.2, 'Kleerebezem': -322.0},
        'Molar mass (g/mol)': 90.0,
    },

    '2.3-butanediol': 'C4H10O2',

    'C5H7O4N-2': {
        'Name': 'glutamate',
        'C': 5,
        'H': 7.0,
        'O': 4.0,
        'N': 1.0,
        'S': 0,
        'Mn': 0,
        'Charge': -2,
        'NOS': 0.3999999999999999,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -940.3,
        'Free-energy of formation (kJ/mol)': {'Amend': -699.62, 'eQ pH=0': -719.7, 'eQ pH=7.5': -344.6, 'Kleerebezem': -697.5},
        'Molar mass (g/mol)': 145.0,
    },

    'glutamate': 'C5H7O4N-2',

    'C6H11O7-1': {
        'Name': 'gluconate',
        'C': 6,
        'H': 11.0,
        'O': 7.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'NOS': 0.3333333333333335,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -1586.9,
        'Free-energy of formation (kJ/mol)': {'Amend': -1154.0, 'eQ pH=0': -1137.9, 'eQ pH=7.5': -649.5, 'Kleerebezem': -1154.0},
        'Molar mass (g/mol)': 195.0,
    },

    'gluconate': 'C6H11O7-1',

    'C12H22O11 (sucrose)': {
        'Name': 'sucrose',
        'C': 12,
        'H': 22.0,
        'O': 11.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -2217.3,
        'Free-energy of formation (kJ/mol)': {'Amend': -1552.4, 'eQ pH=0': -1550.4, 'eQ pH=7.5': -609.1, 'Kleerebezem': -1552.4},
        'Molar mass (g/mol)': 342.0,
    },

    'sucrose': 'C12H22O11 (sucrose)',

    'C12H22O11 (maltose)': {
        'Name': 'maltose',
        'C': 12,
        'H': 22.0,
        'O': 11.0,
        'N': 0.0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -2239.7,
        'Free-energy of formation (kJ/mol)': {'Amend': -1574.6, 'eQ pH=0': -1560.7, 'eQ pH=7.5': -619.4, 'Kleerebezem': -1574.6},
        'Molar mass (g/mol)': 342.0,
    },

    'maltose': 'C12H22O11 (maltose)',


    'Fe+2': {
        'Name': 'Iron (II)',
        'Fe':1,
        'Charge': 2,
        'NOS': 2.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -89.1,
        'Free-energy of formation (kJ/mol)': {'eQ pH=0': -82.1, 'eQ pH=7.5': -82.1, 'Kleerebezem': -78.9},
        'Molar mass (g/mol)': 55.845,
    },

    'Iron (II)': 'Fe+2',
    'Ferrous iron': 'Fe+2',


    'Fe+3': {
        'Name': 'Iron (III)',
        'Fe':1,
        'Charge': 3,
        'NOS': 3.0,
        'Phase': 'aq',
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': -48.5,
        'Free-energy of formation (kJ/mol)': {'eQ pH=0': -11.9, 'eQ pH=7.5': -11.9, 'Kleerebezem': -4.6},
        'Molar mass (g/mol)': 55.845,
    },

    'iron (III)': 'Fe+3',
    'ferric iron': 'Fe+3',

    'C6H15N4O2+1': {
        'Name': 'Arginine',
        'C': 6,
        'H': 15,
        'O': 2,
        'N': 4,
        'S': 0,
        'Mn': 0,
        'Charge': 1,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -624.9,
        'Free-energy of formation (kJ/mol)': {'eQ pH=0': -297.7, 'eQ pH=7.5': 359.4},
        'Molar mass (g/mol)': 175.21,
    }, 

    'arginine': 'C6H15N4O2+1',

    'C23H34N7O17P3S': {
        'Name': 'Acetyl-CoA',
        'C': 23,
        'H': 34,
        'O': 17,
        'N': 7,
        'S': 1,
        'P': 3,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': None,
        'Free-energy of formation (kJ/mol)': {'eQ pH=0': -3349.4, 'eQ pH=7.5': -1762.2},
        'Molar mass (g/mol)': 175.21,
    }, 

    'Acetyl-CoA': 'C23H34N7O17P3S',
    'C2H3O-S-CoA': 'C23H34N7O17P3S',

   'C21H32N7O16P3S': {
        'Name': 'Coenzyme A',
        'C': 21,
        'H': 32,
        'O': 16,
        'N': 7,
        'S': 1,
        'P': 3,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': None,
        'Free-energy of formation (kJ/mol)': {'eQ pH=0': -3213.3, 'eQ pH=7.5': -1709.7},
        'Molar mass (g/mol)': 175.21,
    }, 
    
    'Coenzyme A': 'C21H32N7O16P3S',
    'CoA': 'C21H32N7O16P3S',

    'C6H14O6 (sorbitol)': {
        'Name': 'Sorbitol',
        'C': 6,
        'H': 14,
        'O': 6,
        'N': 0,
        'S': 0,
        'Mn': 0,
        'Charge': 0,
        'NOS': 0.0,
        'Phase': 'aq',
        'Organic': True,
        'Enthalpy of formation (kJ/mol)': -1353.7,
        'Free-energy of formation (kJ/mol)': {'eQ pH=0': -933.8, 'eQ pH=7.5': -334.8},
        'Molar mass (g/mol)': 182.17,
    },

    'sorbitol': 'C6H14O6 (sorbitol)',


    'e-':  {
        'Name': 'Electron',
        'C': 0,
        'H': 0,
        'O': 0,
        'N': 0,
        'S': 0,
        'Mn': 0,
        'Charge': -1,
        'Phase': None,
        'Organic': False,
        'Enthalpy of formation (kJ/mol)': 0,
        'Free-energy of formation (kJ/mol)': {'eQ pH=0': 0, 'eQ pH=7.5': 0},
        'Molar mass (g/mol)': 0,
    },

    'electron': 'e-'
}   
